import { ItemType } from '../models/itemType'

export const ItemTypes: ItemType[] = [
    {
        label: 'Tiara',
        value: 2,
        weight: 2,
        potentialMaterials: [
            {
                label: 'Gold',
                value: 2,
                weight: 2,
            },
        ],
    },
]

export const idea: string[] = [
    'Art - caligraphy',
    'Art - Manuscript',
    'Art - Embroidery',
    'Art - Cushion',
    'Art - Wood relief carvings',
    'Art - Printed textiles',
    'Painting - Watercolours',
    'Painting - Oils',
    'Painting - Enamels',
    'Painting - Watercolours',
    'Painting - Oils',
    'Painting - Enamels',
    'Ceramings - Pottery',
    'Ceramics - Urns',
    'Ceramics - chinaware',
    'Ceramics - figurine',
    'Ceramics - figurine',
    'Glass - Decanters',
    'Glass - goblets',
    'Glass - bowls',
    'Glass - engravings',
    'Stone - Statuette',
    'Stone - Bust',
    'Stone - Plaque',
    'Stone - Carving',
    'Metal - Sculpture',
    'Metal - Furnishing',
    'Metal - Cutlary',
    'Metal - Tools',
    'Jewellery - Ring',
    'Jewellery - Necklace',
    'Jewellery - Brooch',
    'Jewellery - Clasp',
    'Jewellery - Ring',
    'Jewellery - Necklace',
    'Jewellery - Brooch',
    'Jewellery - Pin',
    'Jewellery - Wooden Box',
    'Jewellery - Pendant',
    'Jewellery - Tiara/Crown',
    'Magic Item - Table A',
    'Magic Item - Table B',
    'Magic Item - Table C',
    'Magic Item - Table D',
    'Magic Item - Table E',
    'Magic Item - Table F',
    'Magic Item - Table G',
    'Magic Item - Table H',
    'Magic Item - Table I',
]
