# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Test

on:
  pull_request:
    branches:
      - "*"
jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - run: npm run build --if-present
      - name: Code Climate Coverage
        uses: marsam/codeclimate-action@v1
        with:
          command: npm test
          reporter-id: ${{ secrets.CODECLIMATE_ID }}
      - run: docker image build -t test .
