# This is a basic workflow to help you get started with Actions

name: Publish Image

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Docker Build
      run: docker image build -t daustin/purrito .
    
    - name: Docker Publish
      uses: manusa/actions-publish-docker@v1.0.1
      with:
        # Name of the Docker image
        name: daustin/purrito
        # Tag for the Docker image
        tag: latest
        # Username for Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password for Docker registry
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
