# This is a basic workflow to help you get started with Actions

name: Publish Image and Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Docker Build
        run: docker image build -t daustin/purrito .

      - name: Docker Publish
        uses: manusa/actions-publish-docker@v1.0.1
        with:
          # Name of the Docker image
          name: daustin/purrito
          # Tag for the Docker image
          tag: latest
          # Username for Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password for Docker registry
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Deploy
        run: |
          echo "${{ secrets.AWS_PEM }}" > key.pem
          chmod 400 key.pem
          ssh -oStrictHostKeyChecking=no -i key.pem ec2-user@35.179.80.203 "docker-compose down && docker-compose up -d"

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to AWS.
